# Lab Assignment 1:
# Handwritten Character Recognition (MNIST) with ANN

### Objective
The goal of this assignment is to build and train a simple Artificial Neural Network (ANN) to (from scratch without any library of framework.) recognize handwritten digits. You will use the classic MNIST dataset, a foundational benchmark in the field of machine learning. By completing this assignment, 

### The Dataset: MNIST 
The MNIST (Modified National Institute of Standards and Technology) dataset is a large 
collection of handwritten digits. It contains 60,000 training images and 10,000 testing 
images. Each image is a grayscale picture, 28 pixels wide by 28 pixels high. The digits are 
from 0 to 9. 

In [5]:

# Importing dataset
import pandas as pd 

data = pd.read_csv("/media/escanor/extra/programing/5_Sem/Deep_Learning/Assignments/1 ANN From Scratch/mnist/mnist_train.csv")
data.head(5)

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      5    0    0    0    0    0    0    0    0    0  ...      0      0   
1      0    0    0    0    0    0    0    0    0    0  ...      0      0   
2      4    0    0    0    0    0    0    0    0    0  ...      0      0   
3      1    0    0    0    0    0    0    0    0    0  ...      0      0   
4      9    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Columns: 785 entries, label to 28x28
dtypes: int64(785)
memory usage: 359.3 MB


### Neural Network Architecture
Your task is to implement an ANN with the following three key layers: 


##### 1. Input Layer 
The input to our network will be a single image from the MNIST dataset. Since each image is 
28×28 pixels, we need to flatten it into a one-dimensional array of numbers.  
●  Number of Neurons: 28×28=784 neurons.  
●  Purpose: This layer simply holds the pixel values of the input image. Each neuron corresponds to a single pixel. 


In [26]:
# basic exampple 
import numpy as np

dummydata = np.array(data.iloc[:5,1:])
print(dummydata.shape)
print(dummydata)

(5, 784)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
n1 = 6
input = dummydata.shape[1]
input



784

In [ ]:
def get_input (data) :
    pass

In [6]:
class Neuron:
    pass

class Layer:
    pass

##### 2. Hidden Layer 
The hidden layer is where the network learns to identify patterns and features from the input data, such as lines, curves, and edges.  
●  Number of Neurons: You will use 128 neurons for this layer.  
●  Activation Function: The ReLU (Rectified Linear Unit) activation function should 
be used. It helps the network learn complex relationships in the data.  


##### 3. Output Layer 
The output layer provides the final classification result. Since we are trying to predict one of 
ten possible digits (0-9), this layer will have ten neurons.  
●  Number of Neurons: 10 neurons, one for each digit class (0 through 9).  
●  Activation Function: The Softmax activation function should be used. Softmax will 
convert the outputs into a probability distribution, where the sum of all probabilities is. The neuron with the highest probability corresponds to the predicted digit. 
●  Loss Function: The Categorical Cross-Entropy loss function is appropriate for this 
multi-class classification task. 
 